### ISSUE TITLE
Migration keywords do not take a screenshot on failure

### ISSUE THREAD

**Issue by KleerCoder** [Snooz82/robotframework-browser-migration#3]
If I use a Browser keyword in RF code, I get a screenshot when it fails. But when I use SeleniumLibraryToBrowser keywords, they do not take a screenshot on failure.

Sample outputs can be found at: https://robotframework.slack.com/archives/C015KB1QSDN/p1677627042130679

**Comment by KleerCoder** [comment]
@Snooz82 Any updates?

**Comment by Snooz82** [comment]
Hi,

should be fixed with the 1.0 Release
